//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Devices = new HashSet<Device>();
            this.Drivers = new HashSet<Driver>();
            this.Fleets = new HashSet<Fleet>();
            this.MaintenanceOperation_Company = new HashSet<MaintenanceOperation_Company>();
            this.Pois = new HashSet<Poi>();
            this.SecurityRoutes = new HashSet<SecurityRoute>();
            this.Users = new HashSet<User>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_companytype { get; set; }
        public Nullable<int> id_company { get; set; }
        public string cif { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string fax_number { get; set; }
        public string email_address { get; set; }
        public Nullable<System.DateTime> registry_date_time { get; set; }
        public string map_address { get; set; }
        public string events_email_address { get; set; }
        public Nullable<int> id_drivingrulesconfiguration { get; set; }
        public Nullable<int> id_platform_service { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual DrivingRulesConfiguration DrivingRulesConfiguration { get; set; }
        public virtual PlatformService PlatformService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fleet> Fleets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceOperation_Company> MaintenanceOperation_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poi> Pois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityRoute> SecurityRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
