//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Device_Services = new HashSet<Device_Services>();
            this.DeviceStatus = new HashSet<DeviceStatu>();
            this.Events = new HashSet<Event>();
            this.PendingCommands = new HashSet<PendingCommand>();
            this.Routes = new HashSet<Route>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_vehicle { get; set; }
        public Nullable<int> id_company { get; set; }
        public Nullable<int> id_devicemodel { get; set; }
        public Nullable<int> id_sim { get; set; }
        public string system_id { get; set; }
        public string IMEI { get; set; }
        public string phone_number { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> ip_port { get; set; }
        public Nullable<System.DateTime> keep_alive_date_time { get; set; }
        public string location_string { get; set; }
        public Nullable<System.DateTime> gps_date_time { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<int> fix_quality { get; set; }
        public Nullable<int> satellites_in_use { get; set; }
        public Nullable<int> satellites_in_view { get; set; }
        public Nullable<double> hdop { get; set; }
        public Nullable<double> vdop { get; set; }
        public Nullable<double> pdop { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> course { get; set; }
        public Nullable<double> speed { get; set; }
        public Nullable<int> activity { get; set; }
        public Nullable<double> total_gps_odometer { get; set; }
        public Nullable<double> partial_gps_odometer { get; set; }
        public Nullable<bool> engine_state { get; set; }
        public Nullable<bool> gpdi_1 { get; set; }
        public Nullable<bool> gpdi_2 { get; set; }
        public Nullable<bool> gpdi_3 { get; set; }
        public Nullable<bool> gpdi_4 { get; set; }
        public Nullable<int> gpai_1 { get; set; }
        public Nullable<int> gpai_2 { get; set; }
        public Nullable<int> location_source { get; set; }
        public Nullable<int> battery_level { get; set; }
        public Nullable<bool> battery_charging { get; set; }
        public Nullable<int> activity_time { get; set; }
        public string vehicle_vin { get; set; }
        public Nullable<int> road_max_speed { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual DeviceModel DeviceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device_Services> Device_Services { get; set; }
        public virtual Sim Sim { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceStatu> DeviceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingCommand> PendingCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
    }
}
