//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingRulesConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrivingRulesConfiguration()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int id { get; set; }
        public Nullable<int> speed_limit { get; set; }
        public Nullable<int> daily_driving_time_limit { get; set; }
        public Nullable<int> daily_minimum_driving_time { get; set; }
        public Nullable<int> daily_distance_limit { get; set; }
        public Nullable<int> daily_minimum_distance { get; set; }
        public Nullable<int> rpm_limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
    }
}
