//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id { get; set; }
        public Nullable<int> id_device { get; set; }
        public Nullable<int> id_devicestatus { get; set; }
        public Nullable<int> id_eventtype { get; set; }
        public Nullable<System.DateTime> reception_date_time { get; set; }
        public Nullable<int> id_parameter { get; set; }
        public Nullable<byte> email_sent { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceStatu DeviceStatu { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
