//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPolicy
    {
        public int id { get; set; }
        public Nullable<int> id_event_type { get; set; }
        public Nullable<bool> e_mail { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual User User { get; set; }
    }
}
