//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleet_FleetFeatures
    {
        public int Id { get; set; }
        public Nullable<int> id_fleet { get; set; }
        public Nullable<int> id_fleetfeature { get; set; }
    
        public virtual Fleet Fleet { get; set; }
        public virtual FleetFeature FleetFeature { get; set; }
    }
}
