//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetFeature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FleetFeature()
        {
            this.Fleet_FleetFeatures = new HashSet<Fleet_FleetFeatures>();
        }
    
        public int FleetFeatureId { get; set; }
        public string FleetFeatureName { get; set; }
        public Nullable<int> FleetFeatureCode { get; set; }
        public string FleetFeatureData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fleet_FleetFeatures> Fleet_FleetFeatures { get; set; }
    }
}
