//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GangwayServiceFrame
    {
        public int FrameId { get; set; }
        public string FrameData { get; set; }
        public Nullable<bool> FrameSent { get; set; }
        public Nullable<System.DateTime> InsertionDateTime { get; set; }
        public Nullable<System.DateTime> SendingDateTime { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string ExtraData { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
