//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceOperation_Company
    {
        public int id { get; set; }
        public Nullable<int> id_company { get; set; }
        public Nullable<int> id_maintenanceoperation { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual MaintenanceOperation MaintenanceOperation { get; set; }
    }
}
