//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainData
    {
        public int id { get; set; }
        public string server_ip_address { get; set; }
        public string platform_name { get; set; }
        public string events_mail_sender { get; set; }
        public string host { get; set; }
        public Nullable<int> port { get; set; }
        public string password { get; set; }
    }
}
