//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingCommand
    {
        public int id { get; set; }
        public Nullable<int> id_device { get; set; }
        public string command { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
