//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poi()
        {
            this.Vehicle_Poi = new HashSet<Vehicle_Poi>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_poitype { get; set; }
        public Nullable<int> id_company { get; set; }
        public string name { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string notes { get; set; }
        public Nullable<int> radius { get; set; }
        public Nullable<int> id_polygon { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PoiType PoiType { get; set; }
        public virtual Polygon Polygon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Poi> Vehicle_Poi { get; set; }
    }
}
