//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polygon_Point
    {
        public int id { get; set; }
        public Nullable<int> id_polygon { get; set; }
        public Nullable<int> id_point { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Polygon Polygon { get; set; }
    }
}
