//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int id { get; set; }
        public Nullable<int> id_device { get; set; }
        public Nullable<System.DateTime> gps_date_time_start { get; set; }
        public Nullable<System.DateTime> gps_date_time_end { get; set; }
        public Nullable<int> id_devicestatus_start { get; set; }
        public Nullable<int> id_devicestatus_end { get; set; }
        public Nullable<double> distance { get; set; }
        public Nullable<double> average_speed { get; set; }
        public string start_address { get; set; }
        public string end_address { get; set; }
        public Nullable<double> fuel_consumption { get; set; }
        public Nullable<bool> start_address_completed { get; set; }
        public Nullable<bool> end_address_completed { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceStatu DeviceStatu { get; set; }
        public virtual DeviceStatu DeviceStatu1 { get; set; }
    }
}
