//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> login_date_time { get; set; }
        public string platform { get; set; }
    
        public virtual User User { get; set; }
    }
}
